[build-system]        
requires = [
  "setuptools>=42",
  "scikit-build",
  "numpy",
  "ninja; platform_system!='Windows'"
]
build-backend = "setuptools.build_meta"

[project]
name = "accvlab.on_demand_video_decoder"
version = "0.1.0"
description = "On-demand video decoder (part of the ACCV-Lab package)."
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
    "numpy>=1.22.2",
    "accvlab-build-config>=0.1.0",
]

[project.optional-dependencies]
optional = [
    "pytest",
]

[tool.skbuild]
cmake.source-dir = "ext_impl"
cmake.minimum-version = "3.18"
cmake.install-dir = "accvlab/on_demand_video_decoder" 

[tool.setuptools.packages.find]
where = ["."]
include = ["accvlab.on_demand_video_decoder*"]