[build-system]
requires = ["setuptools>=64", "wheel", "torch>=2.0.0", "scikit-build>=0.17.0", "pybind11>=2.10.0"]
build-backend = "setuptools.build_meta"

[project]
name = "accvlab.example_skbuild_package"
version = "0.1.0"
description = "ACCV-Lab SKBuild Example Package"
requires-python = ">=3.8"
dependencies = [
    "torch>=2.0.0",
    "numpy>=1.22.2",
    "accvlab-build-config>=0.1.0",
]

[project.optional-dependencies]
optional = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["accvlab.example_skbuild_package*"]